window.RIFA_CONFIG = {
  TICKET_PRICE: 10,
  TOTAL_NUMBERS: 100,
  RAFFLE_ID: 'rifa-principal',
  NOTIFICATION_CHANNEL: 'email_sms',
  MERCADO_PAGO_PUBLIC_KEY: 'SUA_PUBLIC_KEY_AQUI',
  API_BASE_URL: '/api'
};
